SET DATASTORE_DATASET=b5plus
SET DATASTORE_EMULATOR_HOST=localhost:8081
SET DATASTORE_EMULATOR_HOST_PATH=localhost:8081/datastore
SET DATASTORE_HOST=http://localhost:8081
SET DATASTORE_PROJECT_ID=b5plus
